# Generated by Django 5.2.6 on 2025-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fget_otp',
            new_name='foget_otp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fget_otp_ts',
            new_name='foget_otp_ts',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fget_token',
            new_name='foget_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='suspended',
            new_name='is_suspended',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_fget',
            new_name='last_forgeted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_ts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
