# Generated by Django 5.2.6 on 2025-09-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_fget_otp_user_foget_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Auth Account', 'verbose_name_plural': 'Auth Accounts'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_account',
        ),
    ]
