# Generated by Django 5.2.6 on 2025-09-21 15:19

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[accounts.validators.validate_phone])),
                ('first_name', models.CharField(max_length=150, validators=[accounts.validators.validate_first_name])),
                ('last_name', models.CharField(blank=True, max_length=150, validators=[accounts.validators.validate_last_name])),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('x', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'db_table': 'user_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.userdetail'),
        ),
    ]
