# Generated by Django 5.2.6 on 2025-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdetail_user_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
